-- ─────────────────────────────────────────────────────────────────────────
-- Realtime access policies for Plan Together rooms.
--
-- ✅ ALREADY APPLIED IN PRODUCTION. This file is a RECORD of what is live,
--    not a change to run. It exists because these policies were applied
--    through the Supabase dashboard and never captured in the repo, which led
--    someone (me) to run `grep realtime supabase/schema.sql` -> 0 and wrongly
--    conclude the rooms were unprotected. Absence from the repo is not
--    absence from the database.
--
-- HOW ROOMS ARE ACTUALLY PROTECTED — two independent controls:
--
--   1. Project Settings -> Realtime -> "Allow public access to channels" = OFF.
--      Without this, RLS on realtime.messages is bypassed and every policy
--      below is decorative. This is the control doing the real work.
--
--   2. The policies below on realtime.messages, restricting plan-* topics
--      (broadcast AND presence) to the `authenticated` role.
--
-- VERIFIED 2026-07-22: `pnpm tsx scripts/prove-group-veto.ts`, which subscribes
-- anonymously on the anon key, fails with "subscribe timeout". Anonymous
-- clients cannot join a room.
--
-- WHAT IS STILL OPEN
--
-- A SIGNED-IN user who guesses a room code can still enter. Codes are 4 chars
-- from a 32-char alphabet (~1M) with no rate limit, and membership is
-- deliberately ephemeral (there is no rooms table), so there is nothing to
-- join against. Accepted for now: rooms are short-lived and contain venue
-- preferences. Closing it means persisting membership, a product decision.
--
-- NOTES IF YOU EVER RE-APPLY THESE
--
--   - Do NOT add `alter table realtime.messages enable row level security`.
--     Supabase enables it by default and the table is owned by
--     supabase_realtime_admin, so it fails with:
--       ERROR: 42501: must be owner of table messages
--   - Keep the `(select realtime.topic())` wrapper. The scalar subquery is
--     evaluated once per statement instead of once per row.
--   - Keep `extension in ('broadcast','presence')`. Rooms use presence for the
--     live member list; filtering to broadcast alone breaks the lobby.
--
-- Verify what is live:
--   select policyname, cmd, roles, qual, with_check
--   from pg_policies
--   where schemaname = 'realtime' and tablename = 'messages';
-- ─────────────────────────────────────────────────────────────────────────

-- Commented out deliberately: these are ALREADY in the database. Uncomment
-- only when rebuilding a project from scratch.

-- create policy "authenticated can read plan-together rooms"
--   on realtime.messages
--   for select
--   to authenticated
--   using (
--     (select realtime.topic()) like 'plan-%'
--     and extension in ('broadcast', 'presence')
--   );

-- create policy "authenticated can write plan-together rooms"
--   on realtime.messages
--   for insert
--   to authenticated
--   with check (
--     (select realtime.topic()) like 'plan-%'
--     and extension in ('broadcast', 'presence')
--   );
