// Stage 1.1 — compute IDF weights for the canonical tag vocabulary from the
// live catalogue and GENERATE lib/tag-idf.ts. Rare, distinctive tags (omakase,
// natural-wine) get a high weight; ubiquitous ones (casual) get a low one, so
// the venue tag-vector reflects what makes a place distinctive, not what every
// place shares.
//
//   idf(tag) = ln(N / df(tag))   — N = visible venues, df = venues with the tag.
//
// Re-run after a canonical_tags backfill or a vocabulary change:
//   pnpm compute-tag-idf

import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { createClient } from "@supabase/supabase-js";
import { writeFileSync } from "fs";
import { ALL_TAGS } from "@/lib/tag-vocabulary";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SERVICE) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}
const supabase = createClient(SUPABASE_URL, SERVICE, {
  auth: { persistSession: false },
});

async function main() {
  const df = new Map<string, number>();
  let n = 0;
  const PAGE = 1000;
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await supabase
      .from("venues")
      .select("canonical_tags")
      .is("hidden_at", null)
      .range(from, from + PAGE - 1);
    if (error) {
      console.error(`read failed: ${error.message}`);
      process.exit(1);
    }
    if (!data || data.length === 0) break;
    for (const row of data) {
      n++;
      // df = number of venues containing the tag (once per venue).
      for (const t of new Set((row.canonical_tags as string[]) ?? [])) {
        df.set(t, (df.get(t) ?? 0) + 1);
      }
    }
    if (data.length < PAGE) break;
  }

  // idf for EVERY vocab tag (df=0 → max weight ln(N), so an unused-but-valid
  // tag a user might pick still counts as highly distinctive).
  const idf: Record<string, number> = {};
  for (const tag of ALL_TAGS) {
    const d = df.get(tag) ?? 0;
    idf[tag] = Math.round(Math.log(n / Math.max(d, 1)) * 1000) / 1000;
  }

  const body = `// GENERATED by scripts/compute-tag-idf.ts — DO NOT EDIT BY HAND.
// IDF weights for the canonical tag vocabulary: idf = ln(N / df). Rare,
// distinctive tags weigh more than ubiquitous ones, so a venue's weighted
// tag-vector reflects what makes it distinctive. Re-run \`pnpm compute-tag-idf\`
// after a canonical_tags backfill or a TAG_VERSION change.
import type { Tag } from "./tag-vocabulary";

export const TAG_IDF_META = {
  n: ${n},
  distinctTags: ${df.size},
  generatedAt: ${JSON.stringify(new Date().toISOString())},
} as const;

export const TAG_IDF: Readonly<Record<Tag, number>> = ${JSON.stringify(idf, null, 2)} as const;
`;
  writeFileSync("lib/tag-idf.ts", body);

  const sorted = [...ALL_TAGS].sort((a, b) => idf[b] - idf[a]);
  console.log(`Wrote lib/tag-idf.ts · N=${n} · ${df.size}/${ALL_TAGS.length} tags seen\n`);
  console.log("Highest weight (most distinctive):");
  for (const t of sorted.slice(0, 6))
    console.log(`  ${t.padEnd(18)} idf ${idf[t]}  (df ${df.get(t) ?? 0})`);
  console.log("Lowest weight (most common):");
  for (const t of sorted.slice(-6))
    console.log(`  ${t.padEnd(18)} idf ${idf[t]}  (df ${df.get(t) ?? 0})`);
}

main().catch((e) => {
  console.error("\nFATAL:", e);
  process.exit(1);
});
