-- ⚠️ OWNER-LEVEL EXECUTION REQUIRED — THIS FILE CANNOT BE APPLIED BY THE
-- NORMAL MIGRATION PATH.
--
-- Verified against the live project 2026-07-29 (read-only):
--   current_user                                  = postgres
--   owner of realtime.messages                    = supabase_realtime_admin
--   pg_has_role(postgres, supabase_realtime_admin) = FALSE
--
-- CREATE POLICY / DROP POLICY require table ownership, so `supabase db push`,
-- the MCP apply_migration tool and any CI migration step will fail here with
--   ERROR: 42501: must be owner of table messages
-- This is the same constraint recorded in supabase/realtime-policies.sql: the
-- live broad policies were created through the Supabase dashboard, not a
-- migration.
--
-- APPLY VIA: the Supabase dashboard SQL editor (or another owner-level
-- mechanism), pasting the statements below verbatim. Then prove the result:
--   EXPECT_STAGE=<2|3> pnpm tsx scripts/verify-room-security.ts
-- The repository copy and the applied database state must stay identical; the
-- verification script is what proves they are.
--
-- ─────────────────────────────────────────────────────────────────────────
-- 0003 · Remove the broad plan-% Realtime policies.
--
-- STEP 3 OF 3 — THE ONLY STEP THAT REMOVES ACCESS. Run it only after
-- `pnpm tsx scripts/verify-room-security.ts` reports the membership path
-- healthy on production (see the doc's "Production verification" section).
--
-- Before: any authenticated user who guessed a room code could read and write
-- that room's channel. After: only recorded, non-departed members of a room
-- that is neither expired nor closed.
--
-- Rollback (immediate, safe): re-create the two policies below verbatim —
-- this is the pre-change state, kept here so a rollback needs no archaeology.
--
--   create policy "authenticated can read plan-together rooms"
--     on realtime.messages for select to authenticated
--     using ((select realtime.topic()) like 'plan-%'
--            and extension in ('broadcast','presence'));
--
--   create policy "authenticated can write plan-together rooms"
--     on realtime.messages for insert to authenticated
--     with check ((select realtime.topic()) like 'plan-%'
--                 and extension in ('broadcast','presence'));
-- ─────────────────────────────────────────────────────────────────────────

drop policy if exists "authenticated can read plan-together rooms"  on realtime.messages;
drop policy if exists "authenticated can write plan-together rooms" on realtime.messages;
